<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="DESKTOP-DJ4FDME" failures="1" tests="1" name="Test(failed)" time="0.096" errors="0" timestamp="2024-05-22T07:13:00 IST">
  <testcase classname="testNGDemo.TestScenario1" name="first_testcase" time="0.036">
    <failure type="java.lang.AssertionError" message="expected [hello1] but found [hello]">
      <![CDATA[java.lang.AssertionError: expected [hello1] but found [hello]
at testNGDemo.TestScenario1.first_testcase(TestScenario1.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- first_testcase -->
  <testcase classname="testNGDemo.TestScenario1" name="second_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- second_testcase -->
  <testcase classname="testNGDemo.TestScenario1" name="third_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- third_testcase -->
  <testcase classname="testNGDemo.TestScenario1" name="forth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- forth_testcase -->
  <testcase classname="testNGDemo.TestScenario1" name="fifth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- fifth_testcase -->
  <testcase classname="testNGDemo.TestScenario1" name="sixth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- sixth_testcase -->
</testsuite> <!-- Test(failed) -->
